name: Sync Repo A into Repo B

on:
  workflow_dispatch: # Manual trigger
  schedule: 
    - cron: '0 2 * * *' # Run daily at 2 AM UTC
  repository_dispatch: # Trigger when new changes are pushed to repo A

jobs:
  sync_repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: Kavindutharaka/b # Replace with repo B's path
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          ref: master

      - name: Verify Repository Access
        run: |
          git remote -v
          git branch -a
          git fetch --all
          
      - name: Clone Repo A into Repo B
        run: |
          git clone https://github.com/Kavindutharaka/a.git sub_a # Clone Repo A into a subdirectory named sub_a
          mv sub_a/* . # Move Repo A contents into the root of Repo B
          rm -rf sub_a # Remove the now-empty subdirectory

      - name: Commit changes
        run: |
          git config --global user.name "Kavindutharaka"
          git config --global user.email "ktliyanapathirana2000@gmail.com"
          git add .
          git commit -m "Sync changes from Repo A" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
