name: Sync Repo A into Repo B

on:
  workflow_dispatch: # Manual trigger
  schedule: 
    - cron: '0 2 * * *' # Run daily at 2 AM UTC
  repository_dispatch: # Triggered when a webhook is sent from Repo A
  push: # Trigger when a new commit is pushed to Repo A
    branches:
      - main

jobs:
  sync_repos:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repo B
        uses: actions/checkout@v3
        with:
          repository: Kavindutharaka/b
          token: ${{ secrets.CUSTOM_GITHUB_TOKEN }}
          ref: master # Checkout the master branch of Repo B

      - name: Clone Repo A into Repo B
        run: |
          git clone https://github.com/Kavindutharaka/a.git sub_a # Clone Repo A into a subdirectory
          mkdir -p ./sub/ # Ensure the target subfolder exists in Repo B
          mv sub_a/* ./sub/ # Move Repo A contents into the 'sub' folder in Repo B
          rm -rf sub_a # Remove the now-empty subdirectory

      - name: Commit changes
        run: |
          git config --global user.name "Kavindutharaka"
          git config --global user.email "ktliyanapathirana2000@gmail.com"
          git add .
          git commit -m "Sync changes from Repo A" || echo "No changes to commit"
          git push origin master
        env:
          GITHUB_TOKEN: ${{ secrets.CUSTOM_GITHUB_TOKEN }} # Use the GITHUB_TOKEN environment variable for authentication
